# Generated by Django 4.2.7 on 2025-02-02 05:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="Question")),
                ("answer", ckeditor.fields.RichTextField(verbose_name="Answer")),
                (
                    "question_hi",
                    models.TextField(
                        blank=True, null=True, verbose_name="Question in Hindi"
                    ),
                ),
                (
                    "answer_hi",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Answer in Hindi"
                    ),
                ),
                (
                    "question_bn",
                    models.TextField(
                        blank=True, null=True, verbose_name="Question in Bengali"
                    ),
                ),
                (
                    "answer_bn",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Answer in Bengali"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["-created_at"],
            },
        ),
    ]
