# Generated by Django 4.2.7 on 2025-02-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("hi", "Hindi"), ("bn", "Bengali")],
                default="en",
                max_length=10,
                verbose_name="Language",
            ),
        ),
    ]
